# Generated by Django 5.2.1 on 2025-05-19 21:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='exploitant_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('exploitant', 'Exploitant'), ('admin', 'Admin')], default='client', max_length=10),
        ),
        migrations.AddField(
            model_name='activity',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='activities', to='api.category'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['name'], name='api_activit_name_743407_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['exploitant'], name='api_activit_exploit_92bab5_idx'),
        ),
    ]
