# Generated by Django 5.2.1 on 2025-06-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_activity_member_price_user_is_member_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='external_form_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_reservable',
            field=models.BooleanField(default=True),
        ),
    ]
